### ISSUE TITLE
Platform not supported -> expected web for windows

### ISSUE THREAD

**Issue by maltitechnostarksolutions** [OakWings/simple_web_camera#1]

**Comment by RednibCoding** [comment]
Simple Web Camera package is only for web. When you try to use it on other platforms you will get an error: `Platform not supported -> expected web`:
![image](https://github.com/user-attachments/assets/a4f8223b-2b23-4d0d-adf8-3fa023b0d1cb)

This error is thrown here: https://github.com/OakWings/simple_web_camera/blob/48645d91623cd055af37fb2e6d2a6d6bf841470b/lib/pages/unsupported.dart#L19

So this is expected behavior, not a bug :) .
